[package]
name = "improv_extfn"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
improv_core_model = { path = "../core_model" }
thiserror.workspace = true
serde.workspace = true
serde_json.workspace = true
chrono.workspace = true
