[package]
name = "improv_cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[[bin]]
name = "improv"
path = "src/main.rs"

[dependencies]
improv_core_model = { path = "../core_model" }
improv_storage_mentat = { path = "../storage_mentat" }
thiserror.workspace = true
serde_json.workspace = true
