[package]
name = "improv_storage_sql"
version.workspace = true
edition.workspace = true
license.workspace = true

[lib]
name = "improv_storage_sql"
path = "src/lib.rs"

[dependencies]
improv_core_model = { path = "../core_model" }
thiserror.workspace = true
serde.workspace = true
postgres = "0.19"

[dependencies.rusqlite]
version = "0.40"
features = ["bundled"]

[dev-dependencies]
serde_json.workspace = true
